In [91]:
from keras.models import Model 
from keras.layers import Input, Dense 
from keras.utils import np_utils 
import numpy as np
from tensorflow.python.ops.variables import trainable_variables
from numpy import genfromtxt

X_train_my = genfromtxt('../UserData/655/trainX_item_655.csv', delimiter=',')
y_train_my = genfromtxt('../UserData/655/trainY_item_655.csv', delimiter=',')
X_test_my = genfromtxt('../UserData/655/testX_item_655.csv', delimiter=',')
y_test_my = genfromtxt('../UserData/655/testY_item_655.csv', delimiter=',')

num_classes_my = 6 # there are 5 classes (1 per rating class)


In [92]:
X_train_my = X_train_my.astype('float32') 
X_train_my = X_train_my.astype('float32')
print(X_train_my.shape)


(401, 19)


In [93]:
Y_train_my = np_utils.to_categorical(y_train_my, num_classes_my) # One-hot encode the labels

Y_test_my = np_utils.to_categorical(y_test_my, num_classes_my) # One-hot encode the labels


In [94]:
input_img_my = Input(shape=(19,))

print(input_img_my)

Tensor("input_6:0", shape=(?, 19), dtype=float32)


In [95]:
x_my = Dense(19, activation='relu')(input_img_my)
print(x_my)

Tensor("dense_40/Relu:0", shape=(?, 19), dtype=float32)


In [96]:
encoded1_my = Dense(15, activation='relu')(x_my)
encoded2_my = Dense(12, activation='relu')(encoded1_my)





In [97]:
y_my = Dense(10, activation='relu')(encoded2_my)

In [98]:
decoded2_my = Dense(12, activation='relu')(y_my)
decoded1_my = Dense(15, activation='relu')(decoded2_my)


In [99]:
z_my = Dense(19, activation='relu')(decoded1_my)
autoencoder_my = Model(input_img_my, z_my)


In [100]:

#encoder is the model of the autoencoder slice in the middle 
encoder_my = Model(input_img_my, y_my)

print(encoder_my)

In [101]:
autoencoder_my.compile(optimizer='adadelta', loss='mse') # reporting the loss

In [102]:
print(X_test_my.shape)

print(X_train_my.shape)

(172, 19)
(401, 19)


In [103]:
autoencoder_my.fit(X_train_my, X_train_my,
      epochs=50,
      batch_size=10,
      shuffle=True,
      validation_data=(X_test_my, X_test_my)
      )



Train on 401 samples, validate on 172 samples
Epoch 1/50
401/401 [==============================] - 1s 3ms/step - loss: 0.6876 - val_loss: 0.4580
Epoch 2/50
401/401 [==============================] - 0s 655us/step - loss: 0.1482 - val_loss: 0.1141
Epoch 3/50
401/401 [==============================] - 0s 703us/step - loss: 0.0877 - val_loss: 0.0891
Epoch 4/50
401/401 [==============================] - 0s 656us/step - loss: 0.0834 - val_loss: 0.0844
Epoch 5/50
401/401 [==============================] - 0s 649us/step - loss: 0.0811 - val_loss: 0.0835
Epoch 6/50
401/401 [==============================] - 0s 665us/step - loss: 0.0790 - val_loss: 0.0788
Epoch 7/50
401/401 [==============================] - 0s 653us/step - loss: 0.0768 - val_loss: 0.0774
Epoch 8/50
401/401 [==============================] - 0s 649us/step - loss: 0.0749 - val_loss: 0.0774
Epoch 9/50
401/401 [==============================] - 0s 669us/step - loss: 0.0730 - val_loss: 0.0750
Epoch 10/50
401/401 [=================

In [104]:
# if you want an encoded flatten representation of every test MNIST
reduced_representation_my =encoder_my.predict(X_test_my)

In [105]:
#encoder is the model of the autoencoder slice in the middle 
encoder_my = Model(input_img_my, y_my)

autoencoder_my.compile(optimizer='adadelta', loss='mse') # reporting the loss

autoencoder_my.fit(X_train_my, X_train_my,
      epochs=50,
      batch_size=10,
      shuffle=True,
      validation_data=(X_test_my, X_test_my))

Train on 401 samples, validate on 172 samples
Epoch 1/50
401/401 [==============================] - 1s 2ms/step - loss: 0.0568 - val_loss: 0.0607
Epoch 2/50
401/401 [==============================] - 0s 777us/step - loss: 0.0566 - val_loss: 0.0606
Epoch 3/50
401/401 [==============================] - 0s 770us/step - loss: 0.0565 - val_loss: 0.0612
Epoch 4/50
401/401 [==============================] - 0s 682us/step - loss: 0.0563 - val_loss: 0.0602
Epoch 5/50
401/401 [==============================] - 0s 694us/step - loss: 0.0561 - val_loss: 0.0602
Epoch 6/50
401/401 [==============================] - 0s 676us/step - loss: 0.0560 - val_loss: 0.0604
Epoch 7/50
401/401 [==============================] - 0s 676us/step - loss: 0.0560 - val_loss: 0.0602
Epoch 8/50
401/401 [==============================] - 0s 667us/step - loss: 0.0559 - val_loss: 0.0602
Epoch 9/50
401/401 [==============================] - 0s 648us/step - loss: 0.0557 - val_loss: 0.0597
Epoch 10/50
401/401 [=================

In [106]:
# if you want an encoded flatten representation of every test MNIST
reduced_representation_my =encoder_my.predict(X_test_my)

In [107]:
out2_my = Dense(6, activation='softmax')(encoder_my.output)
newmodel_my = Model(encoder_my.input,out2_my)

In [108]:
newmodel_my.compile(loss='categorical_crossentropy',
          optimizer='adam', 
          metrics=['accuracy']) 

In [109]:
newmodel_my.fit(X_train_my, Y_train_my,
      epochs=50,
      batch_size=128,
      shuffle=True,
      validation_data=(X_test_my, Y_test_my))

Train on 401 samples, validate on 172 samples
Epoch 1/50
401/401 [==============================] - 1s 2ms/step - loss: 2.9899 - acc: 0.0125 - val_loss: 2.8603 - val_acc: 0.0349
Epoch 2/50
401/401 [==============================] - 0s 74us/step - loss: 2.7143 - acc: 0.0150 - val_loss: 2.6041 - val_acc: 0.0349
Epoch 3/50
401/401 [==============================] - 0s 83us/step - loss: 2.4769 - acc: 0.0150 - val_loss: 2.3829 - val_acc: 0.0349
Epoch 4/50
401/401 [==============================] - 0s 77us/step - loss: 2.2711 - acc: 0.0150 - val_loss: 2.1943 - val_acc: 0.0407
Epoch 5/50
401/401 [==============================] - 0s 80us/step - loss: 2.0987 - acc: 0.0898 - val_loss: 2.0341 - val_acc: 0.3837
Epoch 6/50
401/401 [==============================] - 0s 70us/step - loss: 1.9524 - acc: 0.4339 - val_loss: 1.8982 - val_acc: 0.5291
Epoch 7/50
401/401 [==============================] - 0s 73us/step - loss: 1.8256 - acc: 0.5362 - val_loss: 1.7808 - val_acc: 0.5407
Epoch 8/50
401/401 [====

In [110]:
print(newmodel_my.predict(X_test_my, verbose=1))
print(np.argmax(newmodel_my.predict(X_test_my, verbose=1),axis=1))

scores_my = newmodel_my.evaluate(X_test_my, Y_test_my, verbose=1) 
print(y_test_my)
print("Accuracy: ", scores_my[1])

from sklearn.metrics import confusion_matrix
cfm = confusion_matrix(np.array(y_test_my),np.array(np.argmax(newmodel_my.predict(X_test_my, verbose=1),axis=1)))
print(cfm)

172/172 [==============================] - 0s 2ms/step
[[ 0.00637006  0.01274351  0.1903121   0.62700623  0.14834641  0.01522166]
 [ 0.00679308  0.00917718  0.15293358  0.63658202  0.17884699  0.01566716]
 [ 0.00805046  0.0217279   0.30009222  0.46823391  0.18406098  0.01783453]
 ..., 
 [ 0.01780124  0.02345864  0.19528389  0.53203261  0.19945464  0.03196897]
 [ 0.01505948  0.0444624   0.26378724  0.49185595  0.14974725  0.03508768]
 [ 0.0097586   0.0145137   0.17029296  0.61600941  0.16823184  0.02119351]]
172/172 [==============================] - 0s 83us/step
[3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 2 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 2 3 3 3 3
 3 3 3 3 3 3 2 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
172/172 [==============================] - 0s 129us/step
[ 2.  3.  3.  3.  2.  3.