In [151]:
from keras.models import Model 
from keras.layers import Input, Dense 
from keras.utils import np_utils 
import numpy as np
from tensorflow.python.ops.variables import trainable_variables
from numpy import genfromtxt

X_train_my = genfromtxt('../UserData/655/trainX_655.csv', delimiter=',')
y_train_my = genfromtxt('../UserData/655/trainY_655.csv', delimiter=',')
X_test_my = genfromtxt('../UserData/655/testX_655.csv', delimiter=',')
y_test_my = genfromtxt('../UserData/655/testY_655.csv', delimiter=',')

num_classes_my = 6 # there are 5 classes (1 per rating class)


In [152]:
X_train_my = X_train_my.astype('float32') 
X_train_my = X_train_my.astype('float32')
print(X_train_my.shape)


(483, 20)


In [153]:
Y_train_my = np_utils.to_categorical(y_train_my, num_classes_my) # One-hot encode the labels

Y_test_my = np_utils.to_categorical(y_test_my, num_classes_my) # One-hot encode the labels


In [154]:
input_img_my = Input(shape=(20,))

print(input_img_my)

Tensor("input_10:0", shape=(?, 20), dtype=float32)


In [155]:
x_my = Dense(20, activation='sigmoid')(input_img_my)
print(x_my)

Tensor("dense_63/Sigmoid:0", shape=(?, 20), dtype=float32)


In [156]:
encoded1_my = Dense(15, activation='sigmoid')(x_my)
encoded2_my = Dense(12, activation='sigmoid')(encoded1_my)





In [157]:
y_my = Dense(10, activation='sigmoid')(encoded2_my)

In [158]:
decoded2_my = Dense(12, activation='sigmoid')(y_my)
decoded1_my = Dense(15, activation='sigmoid')(decoded2_my)


In [159]:
z_my = Dense(20, activation='sigmoid')(decoded1_my)
autoencoder_my = Model(input_img_my, z_my)


In [160]:

#encoder is the model of the autoencoder slice in the middle 
encoder_my = Model(input_img_my, y_my)

print(encoder_my)

In [161]:
autoencoder_my.compile(optimizer='adadelta', loss='mse') # reporting the loss

In [162]:
print(X_test_my.shape)

print(X_train_my.shape)

(200, 20)
(483, 20)


In [163]:
autoencoder_my.fit(X_train_my, X_train_my,
      epochs=50,
      batch_size=10,
      shuffle=True,
      validation_data=(X_test_my, X_test_my)
      )



Train on 483 samples, validate on 200 samples
Epoch 1/50
483/483 [==============================] - 2s 4ms/step - loss: 4.2400 - val_loss: 4.0281
Epoch 2/50
483/483 [==============================] - 0s 677us/step - loss: 4.1744 - val_loss: 3.9689
Epoch 3/50
483/483 [==============================] - 0s 661us/step - loss: 4.1115 - val_loss: 3.9127
Epoch 4/50
483/483 [==============================] - 0s 674us/step - loss: 4.0513 - val_loss: 3.8603
Epoch 5/50
483/483 [==============================] - 0s 670us/step - loss: 3.9957 - val_loss: 3.8110
Epoch 6/50
483/483 [==============================] - 0s 681us/step - loss: 3.9442 - val_loss: 3.7682
Epoch 7/50
483/483 [==============================] - 0s 670us/step - loss: 3.9003 - val_loss: 3.7312
Epoch 8/50
483/483 [==============================] - 0s 699us/step - loss: 3.8626 - val_loss: 3.7011
Epoch 9/50
483/483 [==============================] - 0s 669us/step - loss: 3.8321 - val_loss: 3.6766
Epoch 10/50
483/483 [=================

In [164]:
# if you want an encoded flatten representation of every test MNIST
reduced_representation_my =encoder_my.predict(X_test_my)

In [165]:
#encoder is the model of the autoencoder slice in the middle 
encoder_my = Model(input_img_my, y_my)

autoencoder_my.compile(optimizer='adadelta', loss='mse') # reporting the loss

autoencoder_my.fit(X_train_my, X_train_my,
      epochs=50,
      batch_size=10,
      shuffle=True,
      validation_data=(X_test_my, X_test_my))

Train on 483 samples, validate on 200 samples
Epoch 1/50
483/483 [==============================] - 1s 3ms/step - loss: 3.6747 - val_loss: 3.5514
Epoch 2/50
483/483 [==============================] - 0s 681us/step - loss: 3.6746 - val_loss: 3.5513
Epoch 3/50
483/483 [==============================] - 0s 709us/step - loss: 3.6745 - val_loss: 3.5513
Epoch 4/50
483/483 [==============================] - 0s 721us/step - loss: 3.6745 - val_loss: 3.5512
Epoch 5/50
483/483 [==============================] - 0s 691us/step - loss: 3.6744 - val_loss: 3.5511
Epoch 6/50
483/483 [==============================] - 0s 689us/step - loss: 3.6743 - val_loss: 3.5511
Epoch 7/50
483/483 [==============================] - 0s 749us/step - loss: 3.6743 - val_loss: 3.5510
Epoch 8/50
483/483 [==============================] - 0s 898us/step - loss: 3.6742 - val_loss: 3.5510
Epoch 9/50
483/483 [==============================] - 0s 727us/step - loss: 3.6741 - val_loss: 3.5510
Epoch 10/50
483/483 [=================

In [166]:
# if you want an encoded flatten representation of every test MNIST
reduced_representation_my =encoder_my.predict(X_test_my)

In [167]:
out2_my = Dense(6, activation='softmax')(encoder_my.output)
newmodel_my = Model(encoder_my.input,out2_my)

In [168]:
newmodel_my.compile(loss='categorical_crossentropy',
          optimizer='adam', 
          metrics=['accuracy']) 

In [169]:
newmodel_my.fit(X_train_my, Y_train_my,
      epochs=50,
      batch_size=128,
      shuffle=True,
      validation_data=(X_test_my, Y_test_my))

Train on 483 samples, validate on 200 samples
Epoch 1/50
483/483 [==============================] - 1s 2ms/step - loss: 1.5223 - acc: 0.2526 - val_loss: 1.4918 - val_acc: 0.2400
Epoch 2/50
483/483 [==============================] - 0s 63us/step - loss: 1.4959 - acc: 0.3996 - val_loss: 1.4671 - val_acc: 0.5850
Epoch 3/50
483/483 [==============================] - 0s 66us/step - loss: 1.4722 - acc: 0.5611 - val_loss: 1.4432 - val_acc: 0.5850
Epoch 4/50
483/483 [==============================] - 0s 66us/step - loss: 1.4492 - acc: 0.5611 - val_loss: 1.4207 - val_acc: 0.5850
Epoch 5/50
483/483 [==============================] - 0s 64us/step - loss: 1.4269 - acc: 0.5611 - val_loss: 1.3997 - val_acc: 0.5850
Epoch 6/50
483/483 [==============================] - 0s 64us/step - loss: 1.4070 - acc: 0.5611 - val_loss: 1.3798 - val_acc: 0.5850
Epoch 7/50
483/483 [==============================] - 0s 64us/step - loss: 1.3877 - acc: 0.5611 - val_loss: 1.3613 - val_acc: 0.5850
Epoch 8/50
483/483 [====

In [170]:
print(newmodel_my.predict(X_test_my, verbose=1))
print(np.argmax(newmodel_my.predict(X_test_my, verbose=1),axis=1))

scores_my = newmodel_my.evaluate(X_test_my, Y_test_my, verbose=1) 
print(y_test_my)
print("Accuracy: ", scores_my[1])

from sklearn.metrics import confusion_matrix
cfm = confusion_matrix(np.array(y_test_my),np.array(np.argmax(newmodel_my.predict(X_test_my, verbose=1),axis=1)))
print(cfm)

200/200 [==============================] - 1s 3ms/step
[[ 0.02542705  0.03303972  0.24867606  0.54774761  0.13082184  0.01428762]
 [ 0.02524919  0.03246367  0.25298163  0.54429501  0.1309413   0.01406927]
 [ 0.02531124  0.03257883  0.25239184  0.544348    0.13123895  0.01413113]
 ..., 
 [ 0.02553233  0.03303137  0.24987435  0.5465396   0.130688    0.0143343 ]
 [ 0.02530691  0.03255084  0.25286904  0.54387313  0.13129136  0.01410875]
 [ 0.02522945  0.03257915  0.25163555  0.54513258  0.13133782  0.01408541]]
200/200 [==============================] - 0s 129us/step
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
200/200 [==============