In [61]:
from keras.models import Model 
from keras.layers import Input, Dense 
from keras.utils import np_utils 
import numpy as np
from tensorflow.python.ops.variables import trainable_variables
from numpy import genfromtxt

X_train_my = genfromtxt('../UserData/655/trainX_combined_655.csv', delimiter=',')
y_train_my = genfromtxt('../UserData/655/trainY_combined_655.csv', delimiter=',')
X_test_my = genfromtxt('../UserData/655/testX_combined_655.csv', delimiter=',')
y_test_my = genfromtxt('../UserData/655/testY_combined_655.csv', delimiter=',')

num_classes_my = 6 # there are 5 classes (1 per rating class)


In [62]:
X_train_my = X_train_my.astype('float32') 
X_train_my = X_train_my.astype('float32')
print(X_train_my.shape)


(406, 39)


In [43]:
Y_train_my = np_utils.to_categorical(y_train_my, num_classes_my) # One-hot encode the labels

Y_test_my = np_utils.to_categorical(y_test_my, num_classes_my) # One-hot encode the labels


In [44]:
input_img_my = Input(shape=(39,))

print(input_img_my)

Tensor("input_3:0", shape=(?, 39), dtype=float32)


In [45]:
x_my = Dense(39, activation='tanh')(input_img_my)
print(x_my)

Tensor("dense_17/Tanh:0", shape=(?, 39), dtype=float32)


In [46]:
encoded1_my = Dense(15, activation='tanh')(x_my)
encoded2_my = Dense(12, activation='tanh')(encoded1_my)





In [47]:
y_my = Dense(10, activation='tanh')(encoded2_my)

In [48]:
decoded2_my = Dense(12, activation='tanh')(y_my)
decoded1_my = Dense(15, activation='tanh')(decoded2_my)


In [49]:
z_my = Dense(39, activation='tanh')(decoded1_my)
autoencoder_my = Model(input_img_my, z_my)


In [50]:

#encoder is the model of the autoencoder slice in the middle 
encoder_my = Model(input_img_my, y_my)

print(encoder_my)

In [51]:
autoencoder_my.compile(optimizer='adadelta', loss='mse') # reporting the loss

In [52]:
print(X_test_my.shape)

print(X_train_my.shape)

(167, 39)
(406, 39)


In [53]:
autoencoder_my.fit(X_train_my, X_train_my,
      epochs=50,
      batch_size=10,
      shuffle=True,
      validation_data=(X_test_my, X_test_my)
      )



Train on 406 samples, validate on 167 samples
Epoch 1/50
406/406 [==============================] - 1s 2ms/step - loss: 3.2255 - val_loss: 3.3113
Epoch 2/50
406/406 [==============================] - 0s 686us/step - loss: 2.8978 - val_loss: 2.9098
Epoch 3/50
406/406 [==============================] - 0s 679us/step - loss: 2.5392 - val_loss: 2.6087
Epoch 4/50
406/406 [==============================] - 0s 656us/step - loss: 2.3368 - val_loss: 2.4700
Epoch 5/50
406/406 [==============================] - 0s 649us/step - loss: 2.2459 - val_loss: 2.4038
Epoch 6/50
406/406 [==============================] - 0s 632us/step - loss: 2.1984 - val_loss: 2.3613
Epoch 7/50
406/406 [==============================] - 0s 653us/step - loss: 2.1546 - val_loss: 2.3174
Epoch 8/50
406/406 [==============================] - 0s 648us/step - loss: 2.1292 - val_loss: 2.2976
Epoch 9/50
406/406 [==============================] - 0s 617us/step - loss: 2.1111 - val_loss: 2.2825
Epoch 10/50
406/406 [=================

In [54]:
# if you want an encoded flatten representation of every test MNIST
reduced_representation_my =encoder_my.predict(X_test_my)

In [55]:
#encoder is the model of the autoencoder slice in the middle 
encoder_my = Model(input_img_my, y_my)

autoencoder_my.compile(optimizer='adadelta', loss='mse') # reporting the loss

autoencoder_my.fit(X_train_my, X_train_my,
      epochs=50,
      batch_size=10,
      shuffle=True,
      validation_data=(X_test_my, X_test_my))

Train on 406 samples, validate on 167 samples
Epoch 1/50
406/406 [==============================] - 1s 2ms/step - loss: 1.9970 - val_loss: 2.1782
Epoch 2/50
406/406 [==============================] - 0s 610us/step - loss: 1.9958 - val_loss: 2.1770
Epoch 3/50
406/406 [==============================] - 0s 625us/step - loss: 1.9946 - val_loss: 2.1765
Epoch 4/50
406/406 [==============================] - 0s 621us/step - loss: 1.9935 - val_loss: 2.1756
Epoch 5/50
406/406 [==============================] - 0s 646us/step - loss: 1.9926 - val_loss: 2.1748
Epoch 6/50
406/406 [==============================] - 0s 624us/step - loss: 1.9917 - val_loss: 2.1741
Epoch 7/50
406/406 [==============================] - 0s 659us/step - loss: 1.9906 - val_loss: 2.1734
Epoch 8/50
406/406 [==============================] - 0s 632us/step - loss: 1.9897 - val_loss: 2.1731
Epoch 9/50
406/406 [==============================] - 0s 634us/step - loss: 1.9889 - val_loss: 2.1725
Epoch 10/50
406/406 [=================

In [56]:
# if you want an encoded flatten representation of every test MNIST
reduced_representation_my =encoder_my.predict(X_test_my)

In [57]:
out2_my = Dense(6, activation='softmax')(encoder_my.output)
newmodel_my = Model(encoder_my.input,out2_my)

In [58]:
newmodel_my.compile(loss='categorical_crossentropy',
          optimizer='adam', 
          metrics=['accuracy']) 

In [59]:
newmodel_my.fit(X_train_my, Y_train_my,
      epochs=50,
      batch_size=128,
      shuffle=True,
      validation_data=(X_test_my, Y_test_my))

Train on 406 samples, validate on 167 samples
Epoch 1/50
406/406 [==============================] - 0s 1ms/step - loss: 2.0252 - acc: 0.1133 - val_loss: 1.8479 - val_acc: 0.2455
Epoch 2/50
406/406 [==============================] - 0s 57us/step - loss: 1.8792 - acc: 0.1576 - val_loss: 1.7342 - val_acc: 0.2695
Epoch 3/50
406/406 [==============================] - 0s 58us/step - loss: 1.7435 - acc: 0.2685 - val_loss: 1.6296 - val_acc: 0.3832
Epoch 4/50
406/406 [==============================] - 0s 58us/step - loss: 1.6358 - acc: 0.3892 - val_loss: 1.5492 - val_acc: 0.4731
Epoch 5/50
406/406 [==============================] - 0s 60us/step - loss: 1.5536 - acc: 0.4803 - val_loss: 1.4936 - val_acc: 0.5210
Epoch 6/50
406/406 [==============================] - 0s 55us/step - loss: 1.4950 - acc: 0.5074 - val_loss: 1.4530 - val_acc: 0.5329
Epoch 7/50
406/406 [==============================] - 0s 60us/step - loss: 1.4507 - acc: 0.5222 - val_loss: 1.4215 - val_acc: 0.5449
Epoch 8/50
406/406 [====

In [60]:
print(newmodel_my.predict(X_test_my, verbose=1))
print(np.argmax(newmodel_my.predict(X_test_my, verbose=1),axis=1))

scores_my = newmodel_my.evaluate(X_test_my, Y_test_my, verbose=1) 
print(y_test_my)
print("Accuracy: ", scores_my[1])

from sklearn.metrics import confusion_matrix
cfm = confusion_matrix(np.array(y_test_my),np.array(np.argmax(newmodel_my.predict(X_test_my, verbose=1),axis=1)))
print(cfm)

167/167 [==============================] - 0s 1ms/step
[[ 0.01789232  0.02763401  0.23514915  0.58026677  0.0987449   0.04031285]
 [ 0.01597838  0.02719324  0.48510382  0.27046201  0.1493932   0.0518694 ]
 [ 0.02160118  0.03498564  0.26265794  0.53373241  0.10391439  0.04310842]
 ..., 
 [ 0.04211319  0.02582451  0.07069409  0.79870075  0.0453283   0.01733916]
 [ 0.02498754  0.02969855  0.0961271   0.76919228  0.05684377  0.02315088]
 [ 0.016823    0.02854998  0.49342442  0.25319141  0.15034719  0.05766406]]
167/167 [==============================] - 0s 70us/step
[3 2 3 3 3 2 3 2 3 3 2 3 3 3 2 3 2 3 4 3 3 3 3 3 3 3 3 3 3 2 3 3 3 2 3 3 3
 2 2 3 3 3 3 3 2 3 3 3 2 3 3 3 3 3 3 2 3 3 3 3 2 2 3 3 2 2 2 3 3 2 3 2 3 2
 3 2 2 2 2 3 3 2 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 2 3 2 3 3 3 2 3 3 3
 3 3 3 3 3 3 3 3 2 3 2 2 3 3 3 3 3 2 3 3 3 2 2 2 3 3 3 3 3 2 3 3 3 3 3 2 3
 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 2]
167/167 [==============================] - 0s 96us/step
[ 3.  3.  2.  3.  3.  3.  5.  3.  3